// users
const USER_REGISTERED = 'USER_REGISTERED';
const USER_LOGGED_IN = 'USER_LOGGED_IN';

export { USER_REGISTERED, USER_LOGGED_IN };

// posts
const POST_CREATED = 'POST_CREATED';
const POST_UPDATED = 'POST_UPDATED';

export { POST_CREATED, POST_UPDATED };
